### Register User
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "email": "akuntumbal221203@gmail.com",
  "password": "password123",
  "role": "company",
  "fullName": "Wahyu Saputra",
  "phone": "08123456789"
}


### register company
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "akuntumbal221203@gmail.com",
  "password": "Password123",
  "role": "company",
  "companyName": "PT Maju Jaya Sejahtera",
  "industry": "Technology",
  "website": "https://majujaya.co.id",
  "address": "Jl. Sudirman No. 123, Jakarta"

}

### login company
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "akuntumbal221203@gmail.com",
  "password": "Password123"
}

### Register Customer 1
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "email": "bosanonymous684@gmail.com",
  "password": "Password123",
  "role": "user",
  "fullName": "wahyusaputra",
  "phone": "08123456789"
}

### login user 1
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email":"bosanonymous684@gmail.com",
  "password":"Password123"
  }


### Register Customer 2
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "email": "bengkelsarimertaproject@gmail.com",
  "password": "Password123",
  "role": "user",
  "fullName": "satyanatha",
  "phone": "08123456789"
}

### login user 2
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email":"bengkelsarimertaproject@gmail.com",
  "password":"Password123"
  }


### logout
POST http://localhost:4000/auth/logout


